// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright © 2026 Morten Øien Eriksen
// Writes src/styles/styles-splash-themes.css: every built-in theme's values,
// in dark and light, for the tokens the first-visit splash reads, scoped to
// #splash under body[data-splash-theme="<id>"]. index.html's inline script
// picks one of these ids at random before first paint, so the splash wears a
// random theme from its first frame, whatever theme the app itself wears.
//
// The values are the themes' own, as the app applies them: Classic's from
// styles-theme.css and its grid (CLASSIC_LOOK), the others' through
// themeModeSet() in src/ui/themes.js (their colours, the button colours that
// follow them, and their page pattern), a token a theme leaves out keeping
// Classic's value for that mode.
//
//   node tools/splash-themes.mjs        (npm run build:splash-themes)
//
// test/themes-spec-test.js checks the committed file matches this output.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { BUILTIN_THEMES, THEME_TOKENS, themeModeSet, patternLayers, CLASSIC_LOOK } from '../src/ui/themes.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src/styles/styles-splash-themes.css');
const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');

// Classic's values: the dark block, and the light block over it.
function classic() {
  const css = read('src/styles/styles-theme.css');
  const block = (head) => {
    const at = css.indexOf(head);
    if (at < 0) throw new Error(`styles-theme.css has no "${head}" block`);
    const body = css.slice(css.indexOf('{', at) + 1, css.indexOf('}', at));
    return Object.fromEntries([...body.matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)].map((m) => [m[1], m[2].trim()]));
  };
  const dark = block(':root,\n.mode-dark {');
  return { dark, light: { ...dark, ...block(':root[data-mode="light"] {') } };
}

// The tokens the splash reads: its own rules, and the header's text logo,
// which it shows too.
export function splashTokens() {
  const splash = read('src/styles/styles-splash.css');
  const own = splash.slice(splash.indexOf('#splash { display: none; }'));
  const logo = [...read('src/styles/styles-header.css').matchAll(/([^{}]+)\{([^{}]*)\}/g)]
    .filter((m) => /logo-text|tagline-prompt/.test(m[1])).map((m) => m[2]).join('\n');
  const used = new Set([...(own + logo).matchAll(/var\(\s*--([a-z0-9-]+)/g)].map((m) => m[1]));
  return [...THEME_TOKENS.filter((t) => used.has(t) || t === 'pattern-ink'), ...PAGE.filter((t) => used.has(t))];
}
// The page pattern: not a colour token, set from the theme's look.
const PAGE = ['page-pattern', 'page-pattern-size'];

export const SPLASH_THEME_IDS = BUILTIN_THEMES.map((b) => b.id);

export function splashThemesCss() {
  const base = classic();
  const tokens = splashTokens();
  const rules = [];
  for (const { id, name, theme } of BUILTIN_THEMES) {
    for (const mode of ['dark', 'light']) {
      let own;
      if (theme) own = themeModeSet(theme, mode);
      else {
        const grid = patternLayers(CLASSIC_LOOK[mode].pattern, CLASSIC_LOOK[mode].size);
        own = { 'page-pattern': grid.image, 'page-pattern-size': grid.size };
      }
      const decls = tokens.map((t) => `  --${t}: ${own[t] ?? base[mode][t]};`).join('\n');
      const sel = `body[data-splash-theme="${id}"] #splash`;
      rules.push(`/* ${name}, ${mode} */\n${mode === 'light' ? `:root[data-mode="light"] ${sel}` : sel} {\n${decls}\n}`);
    }
  }
  return `/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Morten Øien Eriksen */
/* src/styles/styles-splash-themes.css – GENERATED by tools/splash-themes.mjs
   (npm run build:splash-themes); do not edit by hand. Each built-in theme's
   values for the tokens the first-visit splash reads, in dark and light.
   index.html picks one theme at random before first paint.
   Part of the styles.css @import manifest — cascade order is set there. */

${rules.join('\n')}
/* A system asking for more contrast gets no page pattern, as on the page. */
@media (prefers-contrast: more) {
  body[data-splash-theme] #splash#splash {   /* outranks the light-mode blocks */
    --page-pattern: none;
    --page-pattern-size: auto;
  }
}
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(OUT, splashThemesCss());
  console.log(`wrote ${path.relative(ROOT, OUT)}: ${SPLASH_THEME_IDS.length} themes × 2 modes, ${splashTokens().length} tokens`);
}
